POST http://localhost:3000/api/v1/user
Content-Type: application/json

{
  "first_name": "Jerom",
  "last_name": "Powel",
  "email": "jerom@gmail.com",
  "phone": "12344"
}

###
GET http://localhost:3000/api/v1/user
Content-Type: application/json

{
    "search_by": "",
    "page_no": 1,
    "items_per_page": 20,
    "options": {
        "sort": {
            "field": "first_name",
            "order": "-1"
        }
    }
}